# Generated by Django 5.2.14 on 2026-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoutePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_input", models.CharField(max_length=255)),
                ("finish_input", models.CharField(max_length=255)),
                ("start_lat", models.FloatField()),
                ("start_lng", models.FloatField()),
                ("finish_lat", models.FloatField()),
                ("finish_lng", models.FloatField()),
                ("distance_miles", models.FloatField()),
                ("total_fuel_cost", models.FloatField(blank=True, null=True)),
                ("response_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
